[book]
authors = ["AtHeartEngineer", "curryrasul"]
language = "en"
multilingual = false
src = "src"
title = "Rate-Limiting Nullifier"

[rust]
edition = "2021"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

[output.html.search]
limit-results = 15

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]